from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class JobState(str, Enum):
    QUEUED = "queued"
    PERSONA = "persona"
    ACTS = "acts"
    NARRATIVE = "narrative"
    COMPILE = "compile"
    WORLDS = "worlds"
    PUBLISH = "publish"
    AWAITING_WORLDS = "awaiting_worlds"
    COMPLETED = "completed"
    FAILED = "failed"


class JobRetryRequest(BaseModel):
    """Re-run pipeline from a step. Use `auto` to pick up after the first failed/incomplete step."""

    from_step: str = Field(
        default="auto",
        description="auto | persona | acts | narrative | compile | worlds | full",
    )


class PipelineSessionRequest(BaseModel):
    """User supplies Zielgruppe + Company only; persona_id is generated by the persona agent unless overridden."""

    persona_id: str | None = Field(
        default=None,
        pattern=r"^[a-z][a-z0-9_]*$",
        description="Optional override; otherwise Claude picks a snake_case id from company + audience.",
    )
    target_audience: str = Field(min_length=10)
    company_name: str
    company_description: str
    company_industry: str | None = None
    language: str = "de"
    generate_narrative_previews: bool = True
    generate_worlds: bool = False
    skip_existing_worlds: bool = True
    skip_existing_previews: bool = True


class JobStep(BaseModel):
    id: str
    label: str
    state: JobState
    message: str | None = None


class JobArtifactItem(BaseModel):
    kind: str
    label: str
    path: str
    exists: bool
    public_url: str | None = None


class JobResultSummary(BaseModel):
    display_name: str | None = None
    occupation: str | None = None
    location: str | None = None
    throughline_de: str | None = None
    acts: list[dict] = Field(default_factory=list)


class JobListItem(BaseModel):
    job_id: str
    persona_id: str
    state: JobState
    company_name: str
    target_audience: str
    language: str
    created_at: str
    updated_at: str
    preview_config_url: str | None = None
    error: str | None = None
    generate_worlds: bool = False


class JobStatus(BaseModel):
    job_id: str
    persona_id: str
    state: JobState
    steps: list[JobStep]
    error: str | None = None
    preview_config_url: str | None = None
    world_slugs: list[str] = Field(default_factory=list)
    artifacts: list[JobArtifactItem] = Field(default_factory=list)
    summary: JobResultSummary | None = None
    created_at: str
    updated_at: str
    request: PipelineSessionRequest
    log_tail: str | None = None


class JobEvent(BaseModel):
    type: str
    job: JobStatus | None = None
    message: str | None = None


class PersonaSummary(BaseModel):
    id: str
    display_name: str | None = None
    language: str = "de"
    occupation: str | None = None
    published: bool = False
    preview_config_url: str | None = None
    narrative_preview_acts: list[int] = Field(default_factory=list)


class VoiceoverLineView(BaseModel):
    phase: str
    track_suffix: str | None = None
    at_sec: float = 0
    pause_after_sec: float | None = None
    text: str


class AnchorPlacementView(BaseModel):
    anchor_id: str
    description: str | None = None


class ActCreativeView(BaseModel):
    act: int
    blueprint_path: str
    exists: bool = True
    product_layer: str | None = None
    world_slug: str | None = None
    environment_id: str | None = None
    scene_concept_de: str | None = None
    core_message_de: str | None = None
    nova_role: str | None = None
    voiceover_lines: list[VoiceoverLineView] = Field(default_factory=list)
    beat_duration_sec: float | None = None
    prompt_en: str | None = None
    negative_prompt: str | None = None
    camera_notes: str | None = None
    slug_hint: str | None = None
    anchor_placements: list[AnchorPlacementView] = Field(default_factory=list)
    world_prompt_resolved: str | None = None
    world_prompt_source: str | None = None
    preview_image_url: str | None = None


class PersonaActsCreativeResponse(BaseModel):
    persona_id: str
    acts: list[ActCreativeView]


class VoiceoverLineAudioView(BaseModel):
    text: str
    at_sec: float = 0
    pause_after_sec: float | None = None


class VoiceoverTrackAudioView(BaseModel):
    track_id: str
    act: int | None = None
    line_count: int = 0
    text_preview: str = ""
    text: str = ""
    lines: list[VoiceoverLineAudioView] = Field(default_factory=list)
    audio_exists: bool = False
    audio_url: str | None = None
    estimated_duration_sec: float | None = None


class VoiceoverAudioStatusResponse(BaseModel):
    persona_id: str
    language: str = "de"
    tracks: list[VoiceoverTrackAudioView]
    elevenlabs_configured: bool = False


class VoiceoverGenerateRequest(BaseModel):
    language: str = "de"
    track_ids: list[str] | None = None
    force: bool = False


class VoiceoverGenerateResponse(BaseModel):
    persona_id: str
    language: str = "de"
    generated: list[str] = Field(default_factory=list)
    skipped: list[str] = Field(default_factory=list)
    errors: dict[str, str] = Field(default_factory=dict)
    tracks: list[VoiceoverTrackAudioView]
